channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.7
  - conda-forge::omegaconf
  - conda-forge::einops
  - conda-forge::wandb
